### ISSUE TITLE
Can not write to /tmp when securityContext.readOnlyRootFilesystem set to true

### ISSUE THREAD

**Issue by JulesMac** [knative/specs#98]
Looking at the [spec](https://github.com/knative/specs/blob/main/specs/serving/runtime-contract.md#default-filesystems) it seems that /tmp should be RW but this does not seem to be the case. My test app simply tried to write a file to /tmp - it work when readOnlyRootFilesystem is false (and fails when true)

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: test
  namespace: testns
spec:
  template:
    spec:
      containers:
      - image: "localhost:5000/test:1.0"
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
```
